#! /bin/sh

F=unknown

if command -v which >/dev/null 2>&1; then
    rlwrap ./driver $@
else
    ./driver $@
fi

echo "Object code (LLVM IR)"
echo "-------------------------------------------------"
cat $F.ll

if command -v dot >/dev/null 2>&1; then
    echo "Generating image of AST"
    echo "-------------------------------------------------"
    dot -O -Tpng $F.dot
    if command -v eog >/dev/null 2>&1; then
        echo "View image of AST"
        echo "-------------------------------------------------"
        eog $F*png &> /dev/null
    fi
fi

echo "Compile to assembly"
echo "-------------------------------------------------"
llc $F.ll

echo "Generate executble"
echo "-------------------------------------------------"
clang $F.s src/main/c/bindings.c -lm -o $F.exe

echo "Run the executable:"
echo "-------------------------------------------------"
./$F.exe
